.TH TPM "1" "April 2026" "Toothpaste Picking Manager" "User Commands"
.SH NAME
tpm \- toothpaste picking manager
.SH SYNOPSIS
.B tpm
[\fI\,OPTION\/\fR]... [\fI\,TOOTHPASTES_LIST\/\fR]...
.SH DESCRIPTION
.\" Add any additional description here
.PP
Output toothpaste picking string
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-a\fR, \fB\-\-rating\fR
pick the toothpaste with highest rating

.TP
\fB\-w\fR, \fB\-\-weight\fR
 pick the toothpaste with highest tube weight
.TP
\fB\-j\fR, \fB\-\-json\fR
 output the JSON with last pick info instead toothpaste picking string
.TP
\fB\-v\fR, \fB\-\-version\fR
show the toothpaste picking manager version
.TP
\fB\-x\fR, \fB\-\-random\fR
perform a random toothpaste pick
.TP
\fB\-q\fR, \fB\-\-quiet\fR
the quiet toothpaste pick
.TP
\fB\-l\fR, \fB\-\-list\fR
list the available toothpastes
.TP
\fB\-r\fR, \fB\-\-reset\fR
reset the total toothpaste picks counter
.TP
\fB\-o\fR, \fB\-\-output\fR[=\fI\,PICK_OUTPUT_FILE\/\fR]
output toothpaste picking string or JSON to the text file 
.TP
\fB\-f\fR, \fB\-\-formula\fR[=\fI\,DENTAL_FORMULA\/\fR]
set dental formula eg. 2-2-2-2 
.TP
\fB\-c\fR,\fB\-\-config\fR[=\fI\,CONFIG_FILE\/\fR]
load the custom configuration file
.TP
\fB\-t\fR,\fB\-\-stats\fR[=\fI\,PICK_STATS_FILE\/\fR]
output the pick stats
.TP
\fB\-s\fR,\fB\-\-counter\fR[=\fI\,COUNTER_VALUE\/\fR]
set the total toothpaste picks counter
.TP
\fB\-p\fR,\fB\-\-type\fR[=\fI\,TOOTHPASTE_PICK_TYPE_VALUE\/\fR]
set the toothpaste pick type value
.TP
\fB\-i\fR,\fB\-\-index\fR[=\fI\,TOOTHPASTE_INDEX\/\fR]
pick the toothpaste by index
.TP
\fB\-b\fR,\fB\-\-brand\fR[=\fI\,TOOTHPASTE_BRAND\/\fR]
 pick the toothpaste by brand
.TP
\fB\-z\fR,\fB\-\-timezone\fR[=\fI\,DELTA_HOURS\/\fR]
set the timezone hours [-11,11] lag manually
.TP
\fB\-d\fR,\fB\-\-delta\fR[=\fI\,DELTA_DAYS\/\fR]
pick the toothpaste with default method in the future or the past

.SH CONFIGURATION
.PP
The configuration is located in \f[C]\[ti]/tpm/tpm.conf\f[R] file
It\[cq]s options:
.PP
\f[C]LOAD_CONFIG\f[R] loads the configuration file \f[C]tpm.conf\f[R]
from specific path
.PP
\f[C]USERNAME\f[R] override the username
.PP
\f[C]PICK_TYPE\f[R] set the toothpaste pick type [0,7] number for
\f[C]Default, Random, By index, By brand, Max rating, Max tube mass, Min rating, Min tube mas\f[R]
.PP
\f[C]DENTAL_FORMULA\f[R] set the dental formula eg. 2-2-2-2
.PP
\f[C]VERBOSE\f[R] 0 for the quiet toothpaste pick
.PP
\f[C]TOOTHPASTES\f[R] the toothpastes list CSV full file name
.PP
\f[C]LAST_PICK\f[R] the last pick file location
.PP
\f[C]PICK_STATS\f[R] the pick stats file location
.PP
\f[C]LIST_TOOTHPASTES\f[R] 1 to list the available toothpastes
.PP
\f[C]OUTPUT_JSON\f[R] 1 to output the JSON with toothpaste pick
.PP
\f[C]OUTPUT_FILE\f[R] 1 to output to the file
\f[C]\[ti]tpm/last_pick\f[R]
.PP
\f[C]PICK_INDEX\f[R] pick the toothpaste by this index if
\f[C]PICK_TYPE=2\f[R]
.PP
\f[C]BRAND\f[R] pick the toothpaste by this brand if
\f[C]PICK_TYPE=3\f[R]
.PP
\f[C]RESET_COUNTER\f[R] 1 to reset the toothpaste pick counter
.PP
\f[C]SET_COUNTER\f[R] not 0 to set the toothpaste pick counter
.PP
\f[C]TIMEZONE\f[R] set the timezone hours [-11,11] lag manually
.PP
\f[C]DELTA_DAYS\f[R] pick the toothpaste with default method in the
future or the past

.SH FILES
.PP
\f[C]\[ti]/tpm/toothpastes\f[R] the CSV toothpastes list
.PP
\f[C]\[ti]/tpm/tpm.conf\f[R] the TPM configuration file
.PP
\f[C]\[ti]/tpm/pickstats\f[R] the toothpaste pick stats binary file
.PP
\f[C]\[ti]/tpm/last_pick\f[R] the last toothpaste pick output message string or JSON file

.PP
Toothpastes CSV file contents sample:

\f[C]
.RS
.nf
#Index,Brand string,Tube mass grams,Rating
0,RANDOM TOOTHPASTE 1,100,85
1,RANDOM TOOTHPASTE 2,50,90
2,RANDOM TOOTHPASTE 3,150,100
3,RANDOM TOOTHPASTE 4,50,100
4,Nothing,0,0
.fi
.RE
\f[R]

.SH AUTHOR
Written by notlibrary and others.

.SH COPYRIGHT
License 0-BSD
.br
.SH "SEE ALSO"
https://github.com/notlibrary/tpm

