name: Brush your teeth
on:
  schedule:
    - cron: '14 6 * * *'
  workflow_dispatch: 
  
jobs:
  brush:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch TPM latest release
      uses: robinraju/release-downloader@v1
      with:
        repository: 'notlibrary/tpm'
        latest: true
        fileName: 'tpm-linux-bin-amd64-*'
        extract: true
    - name: Brush
      run: |
        cd /home/runner/work/tpm/tpm/tpm-linux-bin-amd64
        echo "0,RANDOM TOOTHPASTE 1,100,85,Black,Random toothbrush,20,50" > toothpastes
        echo "1,RANDOM TOOTHPASTE 2,50,90,Black,Random toothbrush,20,50" >> toothpastes
        echo "2,RANDOM TOOTHPASTE 3,150,100,Black,Random toothbrush,20,50" >> toothpastes
        echo "3,RANDOM TOOTHPASTE 4,50,100,Black,Random toothbrush,20,50" >> toothpastes
        echo "4,Nothing,0,0,Nothing,Nothing,0,0" >> toothpastes
        echo "USERNAME=notlibrary" > tpm.conf
        echo "FAKE_STATS=1" >> tpm.conf
        echo "MEME=OVER9000" >> tpm.conf
        echo | ./tpm --fake_stats -c tpm.conf toothpastes
