name: Brush your teeth
on:
  workflow_dispatch:
jobs:
  bump:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch latest release
      uses: robinraju/release-downloader@v1
      with:
        latest: true
        fileName: 'tpm-linux-bin-amd64-*'
        extract: true
    # Bump the version number
    - name: Brush
      run: |
        cd /home/runner/work/tpm/tpm/tpm-linux-bin-amd64
        echo | ./tpm toothpastes.sample
        