name: Release Toothpaste Picking Manager

on:
  push:
    tags:
      - "*"

env:
  APP_NAME: tpm-win-bin-amd64  
jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create.outputs.id }}
    steps:
      - uses: softprops/action-gh-release@v2
        id: create
        with:
          tag_name: ${{ github.ref_name }}
          name: TPM 
          draft: false
          prerelease: false
          body: Toothpaste picking manager
          token: ${{ secrets.PAT3 }}
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup VS PS
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1 
        with:
            arch: x64
      - name: Build on Windows
        if: runner.os == 'Windows'
        id: build        
        shell: powershell
        run: |
          nmake.exe /f .\Makefile.msc tpm.exe
          mkdir ${{ env.APP_NAME }}
          cp tpm.exe ${{ env.APP_NAME }}
          cp toothpastes.sample ${{ env.APP_NAME }}
          cp tpm.conf.sample ${{ env.APP_NAME }}
          cp README.md ${{ env.APP_NAME }}
          Compress-Archive -Path tpm-win-bin-amd64 -DestinationPath tpm-win-bin-amd64.zip
          Move-Item -Path tpm-win-bin-amd64.zip -Destination tpm-win-bin-amd64-${{ github.ref_name }}.zip
          Remove-Item -LiteralPath "tpm-win-bin-amd64" -Force -Recurse -Confirm:$false
          Remove-Item -LiteralPath "tpm.exe" -Force -Recurse -Confirm:$false
          Remove-Item -LiteralPath "*.obj" -Force -Recurse -Confirm:$false
          Remove-Item -LiteralPath "tpm.exp" -Force -Recurse -Confirm:$false
          Remove-Item -LiteralPath "tpm.lib" -Force -Recurse -Confirm:$false
          Remove-Item -LiteralPath "tpm.res" -Force -Recurse -Confirm:$false
      - name: Upload to Release Win
        if: runner.os == 'Windows'       
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT3 }}
          files: tpm-win-bin-amd64-${{ github.ref_name }}.zip 
          
      - name: Build on Linux
        if: runner.os != 'Windows'
        shell: bash
        run: |
            make -f tpm-ubuntu.mk tpm docs distr clean
            mv tpm-linux-bin-amd64.tar.gz tpm-linux-bin-amd64-${{ github.ref_name }}.tar.gz
            
      - name: Upload to Release Linux
        if: runner.os != 'Windows'       
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT3 }}
          files: tpm-linux-bin-amd64-${{ github.ref_name }}.tar.gz 

      - name: Reconfigure build env
        if: runner.os != 'Windows'
        shell: bash
        run: |
            autoreconf -ivf
            tar -czf tpm-unix-tarball-amd64.tar.gz /home/runner/work/tpm/tpm
            mv tpm-unix-tarball-amd64.tar.gz tpm-unix-tarball-amd64-${{ github.ref_name }}.tar.gz
      
      - name: Upload Unix tarball to Release
        if: runner.os != 'Windows'
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT3 }}
          files: tpm-unix-tarball-amd64-${{ github.ref_name }}.tar.gz 

     